direction: right
style: {
  fill: LightBlue
  stroke: FireBrick
  stroke-width: 2
  font-size: 100
}
architecture.style.stroke: "#f4a261"
architecture: {
  AWS EC2: {
    amplify: {
      frontend: {
        nextjsApp -> algolia
        nextjsApp -> api: rest api
      }
    }

    backend: {
      containers: {
        nodeApp -> db: {shape: cylinder}
        nodeApp -> cloud watch
      }
    }

    amplify -> redis -> backend
  }
}

deployment: {
  phases: {
    step1: {
      docker compose -> execute dockerfile -> build app -> create docker images
    }
    step2: {
        sh scripts -> push image to ecr
    }
    step3: {
      terraform: {
        apply -> create infra
        apply -> create networks
        apply -> create security groups
        apply -> set IAM permissions
        apply -> file provisoner -> execute -> deploy-scripts
        deploy-scripts -> ecr to ec2 docker containers
      }
    }
    step1 -> step2 -> step3
  }
}
deployment.style.stroke: "deepskyblue"



