# Specified so that objects are written in row-dominant order
grid-rows: 2
grid-columns: 2
grid-gap: 0

classes: {
  header: {
    style.underline: true
  }
}

Feature.class: header
Type.class: header

Login
Next-auth

Datatables
Next-ui

Search
Algolia
